name: patily
description: A new Flutter project.

publish_to: 'none'

version: 1.1.4+9

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Localization
  easy_localization: ^3.0.1

  #video
  video_player: ^2.5.1

  #State Management
  path_provider: ^2.0.11
  provider: ^6.0.4
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1

  #Firebase 
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth:
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1

  #Animation
  lottie: ^2.2.0
  quickalert: ^1.0.1
  smooth_page_indicator: ^1.0.0+2
  
  #Icons
  flutter_svg: ^1.1.3
  font_awesome_flutter: ^10.3.0
  flutter_native_splash:

  #Local Database
  shared_preferences: ^2.0.15

  #Admob
  google_mobile_ads: ^2.3.0
  
  #Image
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.5+3

  #Maps 
  geolocator: ^9.0.2

  # Utility
  url_launcher: ^6.1.7
  app_tracking_transparency: ^2.0.3
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.18.0
  kartal: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  flutter_gen_runner:
  flutter_lints: ^2.0.0

  #App Icon
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/svg/
    - assets/jsons/lang/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
