name: petilla_app_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #State management
  get: ^4.6.5

  #Firebase 
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.0
  firebase_auth: ^3.5.0
  firebase_storage: ^10.3.4

  #Animation
  lottie: ^1.3.0
  quickalert: ^0.0.2
  
  #Icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.3

  # Local Database
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Admob
  google_mobile_ads: ^2.0.1

  # Utility
  dropdown_button2: ^1.6.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  device_preview: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  readmore: ^2.2.0
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

  #Hive
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

  #Icon
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/
    - assets/svg/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
